#!/bin/bash

set -e

pandoc -f markdown -t rst -o README README.md

version="$(grep __version__ kez/__init__.py)"
echo $version

sed -i "s/^__version__.*$/$version/" setup.py  

if [[ "$version" == *dev* ]]; then
    # dev
    python setup.py sdist --formats=gztar,zip
else
    # not dev
    python setup.py sdist --formats=gztar,zip register upload
fi

